[project] 
name = "tinder_for_events"
version = "0.1"
description = "Python AWS lambda function that contains events"

[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend = "setuptools.build_meta"